config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'display_text' => 'entries#show'
  resources :users 
  resources :books
  resources :readings
  resources :vocab_lists
  resources :entries
  

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books
  has_many :users, through: :user_books
  has_many :vocab_lists
  has_many :readings
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :vocab_list_entries
  has_many :vocab_lists, through: :vocab_list_entries	
end

app/models/highlight_instance.rb
class HighlightInstance < ActiveRecord::Base
  belongs_to :user

  def self.increment_instance(word)
  	current_instance = HighlightInstance.find_by(character: word)
    if current_instance == nil
  	  HighlightInstance.create(user_id: current_user.id, character: word, count: 1)
    else
      current_count = current_instance.count
  	  new_count = current_count + 1
  	  current_instance.update_attribute(:count, new_count) 
    end
  end

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # include BCrypt

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
 
  has_secure_password
  # validates :password, presence: true, length: { minimum: 6 }
  
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/vocab_list.rb
class VocabList < ActiveRecord::Base
  belongs_to :book
  has_many :vocab_list_entries
  has_many :entries, through: :vocab_list_entries
end

app/models/vocab_list_entry.rb
class VocabListEntry < ActiveRecord::Base
  belongs_to :vocab_list
  belongs_to :entry
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	if !logged_in?
  		redirect_to login_path
  	else
  		@books = Book.all
  		render :index
  	end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  include SessionsHelper
  def show
  	if request.xhr?  	
  		highlighted_words = params.key(nil)
  		@entry = Entry.find_by(character: highlighted_words)
  		HighlightInstance.increment_instance(highlighted_words)
  		render @entry
  	else
  		p "HIT ELSE"
  	end
  end

end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  
  def show
  	@reading = Reading.find(params[:id])
  end

  def index
  	if !logged_in?
  		redirect_to login_path
  	else
  		@readings = Reading.all
  		render :index
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password,
                                   :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocab_helper.rb
module VocabHelper
end

app/helpers/vocab_list_helper.rb
module VocabListHelper
end

app/helpers/vocab_lists_helper.rb
module VocabListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/index.html.erb
<div id="container">
<h1>Books Index</h1>
<% @books.each do |book| %>
	<h2><%= book.title_chinese %> <%= book.title_english %> <%= book.series %></h2>
<% end %>
</div>

app/views/entries/_entry.html.erb
<div id="show-highlighted-word">
	<table>
	<tr>
	<td class="deck-table-cell col-100"><%=@entry.pinyin%></td>
	<td class="deck-table-cell col-60"><%=@entry.part_of_speech%> </td>
	<td class="deck-table-cell col-150"><%=@entry.definition %></td>
	</tr>
	</table>
	<a class='hide-button' href='hide-form'>Hide</a>
</div>

app/views/entries/show.html.erb
<div id="show-highlighted-word">
	<table>
	<tr>
	<td class="deck-table-cell col-100"><%=@entry.pinyin%></td>
	<td class="deck-table-cell col-60"><%=@entry.part_of_speech%> </td>
	<td class="deck-table-cell col-150"><%=@entry.definition %></td>
	</tr>
	</table>
	<a class='hide-button' href='hide-form'>Hide</a>
</div>

app/views/readings/_reading.html.erb
<h1>Reading Partial</h1>

app/views/readings/index.html.erb
<div id="container">
  <h1>Readings Index</h1>
  <% @readings.each do |reading| %>
	<a href="<%= reading_path(reading.id) %>"><%= reading.title %></a><p></p>
  <% end %>
</div>

app/views/readings/show.html.erb
<div id ="sidebar" class="affix">
</div>
<div id="nav-container">
<h3>Ch. <%= @reading.chapter_id %>: <%=@reading.title %> </h3>
<p></p>
<% content_array = @reading.content.split("/") %>
<% content_array.each do |string| %>
  <p><%= string %> </p>
<% end %>
<p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p>
<p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p><p>*</p>
</div>

app/views/users/new.html.erb
<h1>User Registration Page</h1>
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit "Create my account" %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= @user.email %>'s Profile